### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ender1908** [Jozott00/wokwi-intellij#44]
I want to start the simulation of the platformIO arduino Uno example project of wokwi. But it doesnt start the simulation. With the example project of the esp32 project it works. It only says "Loading Project..."
![image](https://github.com/Jozott00/wokwi-intellij/assets/92157502/9d8c786c-9dad-45ed-8a9b-e212c4adbd6f)

Console is also clear
![image](https://github.com/Jozott00/wokwi-intellij/assets/92157502/46223f84-cc92-4885-9407-80024a5e3936)

Thanks for help!

**Comment by Jozott00** [comment]
Sorry for the late reply, thanks for the report! I will take a look it

**Comment by AshiqAshref** [comment]
i have the same issue but with mega

**Comment by erosinnocenti** [comment]
Same problem here, but with VScode and rp2040 pico

**Comment by duevil** [comment]
I have the same issue in CLion 2025.1.4, with CLion reporting this error in the Wokwi Simulator plugin:

```
Malformed data received: {}

java.lang.Throwable
	at com.github.jozott00.wokwiintellij.simulator.WokwiSimulator.messageReceived(WokwiSimulator.kt:208)
	at com.github.jozott00.wokwiintellij.jcef.impl.JcefBrowserPipe.informSubscribers(JcefBrowserPipe.kt:84)
	at com.github.jozott00.wokwiintellij.jcef.impl.JcefBrowserPipe.onReceive(JcefBrowserPipe.kt:77)
	at com.github.jozott00.wokwiintellij.jcef.impl.JcefBrowserPipe.access$onReceive(JcefBrowserPipe.kt:24)
	at com.github.jozott00.wokwiintellij.jcef.impl.JcefBrowserPipe$1.invoke(JcefBrowserPipe.kt:34)
	at com.github.jozott00.wokwiintellij.jcef.impl.JcefBrowserPipe$1.invoke(JcefBrowserPipe.kt:34)
	at com.github.jozott00.wokwiintellij.jcef.impl.JcefBrowserPipe._init_$lambda$0(JcefBrowserPipe.kt:34)
	at com.intellij.ui.jcef.JBCefJSQuery$1.onQuery(JBCefJSQuery.java:123)
```
